### ISSUE TITLE
Billable flag may not be accurate

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-webbula#11]
We need to know exactly what constitutes as billable according to Webbula and adjust the response parsing accordingly.

**Comment by ros3bud** [comment]
According to Webbula, when there is no error we are billed. When an error is present, we are not billed. To see the details regarding errors in the response, refer to the webbula billing details documentation in the integrations folder.

**Comment by zalary** [comment]
per PR https://github.com/activeprospect/leadconduit-integration-webbula/pull/7#discussion_r30745734 the billable flag was initially implemented such that all 200 responses were marked billable.   If the changes made to the error handling affect that, the billable flag should need to be updated.  Otherwise, the initial implementation should suffice to mark billable events as such.

**Comment by ros3bud** [comment]
Updated per Version 0.2.7
