### ISSUE TITLE
Add corrected address to the Hygiene integration

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-webbula#26]
The current integration doesn't include the `corrected` value when Webbula fixes an address (example: changing `.con` to `.com`. I just confirmed that Webbula does provide it, when applicable, by replacing the value in *email* with the correct address and adding a *corrected* field with the old address. 

Here is their response when I submitted alexj@activeprospect.co**n**
>
 {
  "success": 1,
  "transaction": "7bb2a6fb4e39469ecfef7616b0ceebcf",
  "package_name": "exp_fEHfjy8NcT_1447353660",
  "profile": "ActiveProspect_H",
  "duration": 1.92798709869385,
  "emails": [
    {
      "email": "alexj@activeprospect.com",
      "corrected": "alexj@activeprospect.con",
      "result": "clean"
    }
  ],
  "errors": [],
  "total_hygiened": 0,
  "prices": "clean"
}

And here is a response when an address has not been corrected:
>
{
  "success": 1,
  "transaction": "8f4a949fad70998b09b6b5c8eb78a0ac",
  "package_name": "exp_tfMRc84agv_1447353623",
  "profile": "ActiveProspect_H",
  "duration": 4.3690140247345,
  "emails": [
    {
      "email": "alexs@activeprospect.com",
      "result": "clean"
    }
  ],
  "errors": [],
  "total_hygiened": 0,
  "prices": "clean"
}

**Comment by jgrayson676** [comment]
How should the integration behave if Webbula doesn't return a corrected email?

The 'Email Data Append' endpoint currently has a `corrected` field which only contains an email **if** Webbula returns a corrected email (it is set to `null` otherwise). I think it would be easier for mappings if the `corrected` field contained either the corrected email returned by Webbula or the original if it didn't need correction. This would make it essentially a 'most correct' field, allowing it to be used in mappings without needing to worry about whether or not it is set to `null`. A different name might be better in that case, as calling it 'corrected' when it might be set to the original value could be a cause of confusion.

**Comment by alexj** [comment]
Good question. We should follow the pattern we set in the Email Data Append integration. That will allow flow creators to detect if an address was corrected or not based on whether the field has a value. This also ensures that we're consistent with the existing integration.
